version: '3.8'

services:
  python_app:
    build: .
    volumes:
      - .:/usr/src/app
    # Use host network if you want to run it on the host network
    network_mode: host
    # Rest of your configuration...
